[package]
name = "opy-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "OPy HIR to canonical Workshop WIR integration compiler"

[lints]
workspace = true

[dependencies]
opy-rs.workspace = true
opy-macro-js = { path = "../opy-macro-js", version = "0.1.3" }
serde.workspace = true
sha2 = "0.10"
workshop-rs.workspace = true

[dev-dependencies]
serde_json.workspace = true
