globalvar g

rule "1488 x":
    g = 0

rule "account":
    g = 1

rule "Admin":
    g = 2

rule "ass":
    g = 3

rule "class":
    g = 4

rule "Bass ass!":
    g = 5

rule "battlenet":
    g = 6

rule "bliz":
    g = 7

rule "blizzaard":
    g = 8

rule "blizzard":
    g = 9

rule "blow":
    g = 10

rule "bnet":
    g = 11

rule "brazil":
    g = 12

rule "canada":
    g = 13

rule "denmark":
    g = 14

rule "england":
    g = 15

rule "finland":
    g = 16

rule "fuck":
    g = 17

rule "goddamn":
    g = 18

rule "ireland":
    g = 19

rule "netherlands":
    g = 20

rule "norway":
    g = 21

rule "poland":
    g = 22

rule "polish":
    g = 23

rule "sanctuary":
    g = 24

rule "satan":
    g = 25

rule "singapore":
    g = 26

rule "shit":
    g = 27

rule "sweden":
    g = 28

rule "switzerland":
    g = 29

rule "Rigger":
    g = 30

rule "r i g g e r":
    g = 31

rule "trigger x":
    g = 32

rule "bnet_x":
    g = 33

rule "Admin Account SHIT":
    g = 34


rule "assx":
    g = 35

rule "blizx":
    g = 36

rule "blizzaardx":
    g = 37

rule "blowx":
    g = 38

rule "bnetx":
    g = 39

rule "brazilx":
    g = 40

rule "canadax":
    g = 41

rule "denmarkx":
    g = 42

rule "englandx":
    g = 43

rule "finlandx":
    g = 44

rule "irelandx":
    g = 45

rule "netherlandsx":
    g = 46

rule "norwayx":
    g = 47

rule "polandx":
    g = 48

rule "polishx":
    g = 49

rule "sanctuaryx":
    g = 50

rule "satanx":
    g = 51

rule "singaporex":
    g = 52

rule "swedenx":
    g = 53

rule "switzerlandx":
    g = 54

rule "r i gger":
    g = 55

rule "rigger":
    g = 56
